language: cpp

before_install:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libeigen3-dev 
  - sudo apt-get install -y libpcl-all
  - ./install-lcm.sh