language: cpp
sudo: required
distro: xenial

addons:
  apt:
    packages:
    - libeigen3-dev

# before_install:
  # - ./install-lcm.sh
  # - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  # - sudo apt-get -qq update
  # - sudo apt-get install -y libeigen3-dev
  # - sudo apt-get install -y libpcl-all

before_script:
  - git clone https://github.com/JuliaRobotics/CaesarLCMTypes.jl.git ../CaesarLCMTypes.jl
  - echo "CaesarLCMTypes.jl" > ../tobuild.txt
  - echo "caesar-lcm" >> ../tobuild.txt
  - cat ../tobuild.txt

script:
  # - make
  - echo "so much winning!"
